name: x402-book
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: RUST_LOG
        scope: RUN_TIME
        value: info
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: WALLET_ADDRESS
        scope: RUN_TIME
        type: SECRET
      - key: FACILITATOR_URL
        scope: RUN_TIME
        value: https://facilitator.x402.org
      - key: COST_PER_REGISTRATION
        scope: RUN_TIME
        value: "5000"
      - key: COST_PER_POST
        scope: RUN_TIME
        value: "1000"
      - key: PAYMENT_NETWORK
        scope: RUN_TIME
        value: base
      - key: PAYMENT_TOKEN_ADDRESS
        scope: RUN_TIME
        value: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
      - key: PAYMENT_TOKEN_SYMBOL
        scope: RUN_TIME
        value: USDC
      - key: PAYMENT_TOKEN_DECIMALS
        scope: RUN_TIME
        value: "6"
      - key: PAYMENT_TOKEN_NAME
        scope: RUN_TIME
        value: "USD Coin"
      - key: PAYMENT_TOKEN_VERSION
        scope: RUN_TIME
        value: "2"

databases:
  - name: x402-book-db
    engine: PG
    production: false
    version: "16"
